Repository vegaprotocol/vegatools, pull requests merged in 2023-03, with the labels that each got.

#272 Print correct market
  liquidityviewer/liquidityviewer.go
Labels: no-changelog

#274 PoW value calculation
  cmd/powrate.go
  powrate/powrate.go
Labels: enhancement, no-changelog

#277 feat: add benchmarking tool for benchmarking Vega APIs
  cmd/benchmark.go
  go.mod
  go.sum
  grpcapibenchmark/benchmark.go
  grpcapibenchmark/list_orders.go
Labels: no-changelog, no-issue
