Repository vegaprotocol/vegatools, pull requests merged in 2023-08, with the labels that each got.

#300 Remove stale sub tools
  CHANGELOG.md
  README.md
  checkpoint/parse.go
  checkpoint/type.go
  cmd/checkpoint.go
  cmd/difftool.go
  cmd/snapshotdb.go
  cmd/stream.go
  difftool/diff/snapshotdb.go
  eventpersister/eventpersister.go
  eventrate/eventrate.go
  eventsource/datanode_eventsource.go
  go.mod
  go.sum
  stream/stream.go
  streamlatency/streamlatency.go
Labels: vegatools

#298 feat: add pagination to the parties request in data-node client for the difftool
  CHANGELOG.md
  difftool/diff/datanode_client.go
Labels: no-issue

#301 Update perftool to support SLA
  CHANGELOG.md
  cmd/perftest.go
  go.mod
  perftest/perftest.go
  perftest/wallet.go
Labels: enhancement, vegatools
